name: Test Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Database
        required: true
        options:
          - Postgres
          - MongoDB

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Run Gradle Project
        run: ./gradlew run
        env:
          LIQUIBASE_OPERATIONS: ${{ github.event.inputs.environment }}
          DATASOURCE_URL: ""
          DATASOURCE_USERNAME: "engine_service_user"
          DATASOURCE_PASSWORD: "MYPassword"

      - name: Build with Gradle
        run: ./gradlew build
        env:
          LIQUIBASE_OPERATIONS: ${{ github.event.inputs.environment }}
          DATASOURCE_URL: ""
          DATASOURCE_USERNAME: "engine_service_user"
          DATASOURCE_PASSWORD: "MuPassword"
