name: Test Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Database
        required: true
        options:
          - Postgres
          - MongoDB

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Run Gradle Project
        run: ./gradlew bootRun --args='--spring.profiles.active=prod'
        env:
          LIQUIBASE_OPERATIONS: ${{ github.event.inputs.environment }}


      - name: Build with Gradle
        run: ./gradlew build
        env:
          LIQUIBASE_OPERATIONS: ${{ github.event.inputs.environment }}

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: build/libs/*.jar  # Adjust the path if your JAR file is located elsewhere
